### ISSUE TITLE
[FE] 상품 상세 페이지 구현

### ISSUE THREAD

**Issue by yesolyo** [codesquad-members-2023-proj02-team04/second-hand#108]
## ☑️ 진행할 작업

- 상품 상세페이지를 구현합니다.

## 📝 TODO

- [ ] : id에 맞게 상세 페이지가 나오게 설정합니다.
- [ ] : 판매중이나 ...버튼 클릭 시 모달 창이 나올 수 있게 구현 합니다.
- [ ] : 모달 창은 공통 컴포넌트에서 사용 할 수 있다고 판단하여 공통 컴포넌트로 구현합니다.
- [ ] : 상품 상세 글을 구현합니다.
- [ ] : 이미지를 옆으로 넘길 수 있게 구현합니다.

## ⚙️ 기타

- 기획서를 참고하였습니다.
