### ISSUE TITLE
[FE] useEffect 커스텀 훅 컴포넌트 구현

### ISSUE THREAD

**Issue by sjuhan123** [codesquad-members-2023-proj02-team04/second-hand#11]
## ☑️ 진행할 작업

useFetch 커스텀 훅 컴포넌트 구현

## 📝 TODO

- [x] : useFetch 커스텀 훅 테스트 코드를 구현한다
- [x] : useFetch 커스텀 훅을 구현한다.
- [x] : useFetch 커스텀 훅을 테스트한다.
