### ISSUE TITLE
[FE] 전반적인 뷰 수정 및 구현

### ISSUE THREAD

**Issue by sjuhan123** [codesquad-members-2023-proj02-team04/second-hand#132]
## ☑️ 진행할 작업

전반적인 뷰 수정 및 구현

## 📝 TODO

- [x] : 데스크탑뷰에서의 레이아웃 수정
  - [x] : 데스크탑뷰 대응을 위해 전반적인 css 수정 - media query 활용
  - [x] : 데스크탑뷰용 배경 적용 및 프로젝트 소개 컴포넌트 구현
- [x] : 에러 발생시 노출될 에러 화면 구현
- [ ] : 상품 목록 없을 때 노출될 컴포넌트 구현
- [x] : tabBar 디자인 수정
