### ISSUE TITLE
[BE] 로그인 인증 구현하기

### ISSUE THREAD

**Issue by ninaaano** [codesquad-members-2023-proj02-team04/second-hand#22]
## ☑️ 진행할 작업
- 로그인 인증만 구현하기 
- 토큰에 데이터 담기 

## 📝 TODO

- [x] : 깃허브 OAuth 사용하여 로그인 인증 구현하기 
- [ ] : JWT 토큰 사용법 학습하기 
- [ ] : 토큰에 유저 데이터 담아 반환하기
