### ISSUE TITLE
[FE] navigation bar 구현

### ISSUE THREAD

**Issue by yesolyo** [codesquad-members-2023-proj02-team04/second-hand#35]
## ☑️ 진행할 작업
- 공통 컴포넌트인 navigation bar를 구현한다.

## 📝 TODO
- [ ] : home nav bar를 구현한다.
- [ ] : modal nav bar를 구현한다.
- [ ] : modal search bar를 구현한다.
- [ ] : segmentedPicker nav bar를 구현한다.
- [ ] : backButton nav bar를 구현한다.

## ⚙️ 기타
- 기획서를 참고하였습니다.
