### ISSUE TITLE
[BE] FE 서버 자동배포

### ISSUE THREAD

**Issue by ninaaano** [codesquad-members-2023-proj02-team04/second-hand#7]
## ☑️ 진행할 작업

도커 사용하여 배포

## 📝 TODO

- [x] : 로컬에 도커 이미지 만들기
- [x] : 도커 허브에 이미지 올리기
- [x] : EC2에서 내려받아서 실행하기
- [x] : 자동 배포

## ⚙️ 기타
시레의 특강 예정

**Comment by ninaaano** [comment]
시레 선생님이 다음주에 알려주신다 하셨습니다 bb
