### ISSUE TITLE
[FE] 물품등록하기 페이지 구현

### ISSUE THREAD

**Issue by yesolyo** [codesquad-members-2023-proj02-team04/second-hand#73]
## ☑️ 진행할 작업
- 물품 등록하기 페이지 구현작업입니다.

## 📝 TODO

- [ ] : 파일 이미지 클릭 시, 이미지 보이게 표시
- [ ] : 입력 후 1초 뒤  카테고리 보이게 표시
- [ ] : 옆에 > 버튼 클릭 시 카테고리 리스트 표시
- [ ] : 글 제목, price, 세부 글 작성 구현

## ⚙️ 기타

- 기획서를 추가하였습니다.
