### ISSUE TITLE
[FE] 물품 작성 페이지 카테고리 ,이미지 업로드 기능 상태 관리

### ISSUE THREAD

**Issue by yesolyo** [codesquad-members-2023-proj02-team04/second-hand#80]
## ☑️ 진행할 작업

- 물품 작성 페이지 카테 고리, 이미지 업로드 기능 상태 관리를 적용합니다.
## 📝 TODO

- [ ] : 이미지 업로드 기능 
  - [ ] : 10개 까지 미리보기 가능 그 이후에는 버튼을 비 활성화합니다.
  - [ ] : 이미지 업로드를 취소시, 버튼이 활성화 됩니다.
  - [ ] : 비 활성화가 되면 이미지 업로드 버튼이 색상이 변경됩니다.
  - [ ] : 이미지 업로드 버튼의 모습이 망가지는 현상을 고칩니다.
 
 - [ ] : 카테고리 기능 
   - [ ] : 카테고리에서 카테고리 선택 시, 세션에 저장합니다.
   - [ ] : 그 전 페이지에서 다시 돌아갔다가 다시 와도 카테고리 선택된 부분이 남아있습니다.

## ⚙️ 기타
- 기획서를 참고하였습니다.
